[2025-05-05 17:47:40,890] 20 root - INFO - \U0001f680 Starting Eye Disease Detection Pipeline Execution
[2025-05-05 17:47:40,890] 28 root - INFO - \U0001f4e5 Initiating Data Ingestion
[2025-05-05 17:49:23,596] 32 root - INFO - Copied input data to feature store at Artifacts\05_05_2025_17_47_38\data_ingestion\feature_store
[2025-05-05 17:50:54,177] 67 root - INFO - Train and Test split completed.
[2025-05-05 17:50:54,178] 81 root - INFO - Data Ingestion process completed.
[2025-05-05 17:50:54,178] 34 root - INFO - \u2705 Initiating Data Validation
[2025-05-05 17:50:54,178] 81 root - INFO - Starting Data Validation Process...
[2025-05-05 17:50:54,185] 75 root - INFO - Drift report saved at Artifacts\05_05_2025_17_47_38\data_validation\drift_report\report.yaml
[2025-05-05 17:50:54,186] 40 root - INFO - \U0001f501 Initiating Data Transformation
[2025-05-05 17:50:54,186] 52 root - INFO - Entered initiate_data_transformation method
[2025-05-05 17:50:54,186] 54 root - INFO - \U0001f501 Starting Data Transformation
[2025-05-05 17:50:54,187] 74 root - INFO - \U0001f5bc\ufe0f Transforming and saving training images...
[2025-05-05 17:52:17,619] 77 root - INFO - \U0001f5bc\ufe0f Transforming and saving validation images...
[2025-05-05 17:57:39,921] 87 root - INFO - \u2705 Data Transformation completed successfully.
[2025-05-05 17:57:39,921] 46 root - INFO - \U0001f9e0 Initiating Model Training
[2025-05-05 17:57:46,335] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C773879600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 17:57:54,685] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77387A0B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 17:58:06,981] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77387A740>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 17:58:27,819] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77387A440>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 17:59:04,529] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C77387A530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:00:13,315] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C773879DE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-05 18:02:17,394] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C773878340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
