[2025-05-09 01:56:16,463] 148 numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2025-05-09 01:56:16,464] 160 numexpr.utils - INFO - NumExpr defaulting to 8 threads.
[2025-05-09 01:56:19,436] 20 root - INFO - \U0001f680 Starting Eye Disease Detection Pipeline Execution
[2025-05-09 01:56:19,436] 28 root - INFO - \U0001f4e5 Initiating Data Ingestion
[2025-05-09 01:56:34,088] 32 root - INFO - Copied input data to feature store at Artifacts\05_09_2025_01_56_16\data_ingestion\feature_store
[2025-05-09 01:57:50,751] 67 root - INFO - Train and Test split completed.
[2025-05-09 01:57:50,752] 81 root - INFO - Data Ingestion process completed.
[2025-05-09 01:57:50,752] 34 root - INFO - \u2705 Initiating Data Validation
[2025-05-09 01:57:50,752] 81 root - INFO - Starting Data Validation Process...
[2025-05-09 01:57:50,758] 75 root - INFO - Drift report saved at Artifacts\05_09_2025_01_56_16\data_validation\drift_report\report.yaml
[2025-05-09 01:57:50,759] 40 root - INFO - \U0001f501 Initiating Data Transformation
[2025-05-09 01:57:50,759] 52 root - INFO - Entered initiate_data_transformation method
[2025-05-09 01:57:50,759] 54 root - INFO - \U0001f501 Starting Data Transformation
[2025-05-09 01:57:50,759] 74 root - INFO - \U0001f5bc\ufe0f Transforming and saving training images...
[2025-05-09 02:00:01,219] 77 root - INFO - \U0001f5bc\ufe0f Transforming and saving validation images...
[2025-05-09 02:08:38,351] 87 root - INFO - \u2705 Data Transformation completed successfully.
[2025-05-09 02:08:38,351] 46 root - INFO - \U0001f9e0 Initiating Model Training
[2025-05-09 02:08:43,551] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39856AE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-09 02:08:52,104] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39C87C80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-09 02:09:04,846] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39CE4320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-09 02:09:25,016] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39CE5B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-09 02:10:01,895] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39CE5D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-09 02:11:10,086] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39CE5E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
[2025-05-09 02:13:14,142] 870 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018F39CE6000>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=EyeDiseaseDetection
